### PR TITLE
#1: Fix auto answer not working.

### LINKED ISSUE #1: Auto answer only works when using int, not bool
In the documentation the auto answer is documented as a bool. The auto answer does only work when using an integer.

### PR DESCRIPTION
**Pull request by stijnbuurman**
Makes sure a number is send, as a bool is not supported by ClearVox.

Fixes #1

### CODE REVIEW

File: src/CallControl/Action/MakeCallAction.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ export class MakeCallAction extends Action {
         super('makeCall', {
             number: number,
             phone: phone,
-            auto_answer: autoAnswer,
+            auto_answer: autoAnswer ? Number(autoAnswer) : 0,
```
Comment (CILLERt) [inline src/CallControl/Action/MakeCallAction.ts]: This is invalid, not setting auto answer should use the system defined setting. Not disable auto answer.

**Review by CILLERt — CHANGES_REQUESTED** [review]

File: src/CallControl/Action/MakeCallAction.ts (hunk 1 above)
Comment (stijnbuurman) [reply src/CallControl/Action/MakeCallAction.ts]: True, i changed it to -1 which means fetch it from the users' settings

**Review by CILLERt — APPROVED** [review]
